version: '3'
services:
  frontend:
    image: meghnabm/frontend:${GITHUB_SHA}
    restart: unless-stopped

  backend:
    image: meghnabm/backend:${GITHUB_SHA}
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
