events {}

http {
  server {
    listen 80;

    # Frontend served at /
    location / {
      proxy_pass http://frontend:80;
    }

    # Backend health check served at /health
    location /health {
      proxy_pass http://backend:5000;
    }
  }
}

